### ISSUE TITLE
Error when attemping to use V1 Routes package: Error: Error loading Remix config at remix.config.js

### ISSUE THREAD

**Issue by cliffordfajardo** [remix-run/v1-compat-utils#33]
Created a repo to reproduce here:
https://github.com/cliffordfajardo/remix_express_v1_to_v2_routes_bug

## Steps to Reproduce

1. Create a Remix app using V1** _(I chose the express template in my repo)_
```
npx create-remix@1.19.3
```

3. Update all `@remix-run/*` dependencies to version `2.0.1`
4. Add `@remix-run/v1-route-convention` package to continue using V1 routes
5. Update remix.config.js to use `@remix-run/v1-route-convention` package
6. Run `npm run dev` & the error will appear

```
💿  remix dev

Error: Error loading Remix config at /Users/cfajardo/Desktop/remix_express_v1_to_v2_routes_bug/remix.config.js
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/cfajardo/Desktop/remix_express_v1_to_v2_routes_bug/node_modules/@remix-run/dev/dist/config/routes' imported from /Users/cfajardo/Desktop/remix_express_v1_to_v2_routes_bug/node_modules/@remix-run/v1-route-convention/dist/index.mjs
Did you mean to import @remix-run/dev/dist/config/routes.js?
    at Object.readConfig (/Users/cfajardo/Desktop/remix_express_v1_to_v2_routes_bug/node_modules/@remix-run/dev/dist/config.js:72:13)
    at async Object.dev (/Users/cfajardo/Desktop/remix_express_v1_to_v2_routes_bug/node_modules/@remix-run/dev/dist/cli/commands.js:179:18)
    at async Object.run (/Users/cfajardo/Desktop/remix_express_v1_to_v2_routes_bug/node_modules/@remix-run/dev/dist/cli/run.js:192:7)
```

NOTE: all of these steps have been applied is in the bug reproduction repo:
https://github.com/cliffordfajardo/remix_express_v1_to_v2_routes_bug

**Comment by cliffordfajardo** [comment]
Interestingly, I changed the `exports.import` value inside of the `package.json` file of `@remix-run/v1-route-convention` to use the `dist/index.js` instead of `dist/index.mjs`, then ran `npm run dev` and it worked

![CleanShot 2023-10-01 at 13 22 26@2x](https://github.com/remix-run/v1-compat-utils/assets/6743796/2d037645-b331-4c50-a047-c4a9f0331267)


I also noticed @jacob-ebey made a PR a few days ago but
![CleanShot 2023-10-01 at 13 23 34@2x](https://github.com/remix-run/v1-compat-utils/assets/6743796/c408b44b-1d8e-413a-ad4c-b65e4c75d174)

it doesnt seem to be published on npm  yet since  I see the change on the master branch, but when I look at my `node_modules` folder, I see the old `exports` content
![CleanShot 2023-10-01 at 13 26 44@2x](https://github.com/remix-run/v1-compat-utils/assets/6743796/12101366-1e80-48fb-b44e-878b1bace9e4)

**Comment by cliffordfajardo** [comment]
Confirmed locally that changing `exports` object worked in my local project:


```
// BEFORE:
"exports": {
    "./package.json": "./package.json",
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/index.mjs",
      "require": "./dist/index.js"
    }
  },


// AFTER
  "exports": {
    "./package.json": "./package.json",
    ".": {
      "types": "./dist/index.d.ts",
      "default": "./dist/index.js"
    }
  },
```
